# Generated by Django 4.1.2 on 2022-11-23 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_alter_ticketbooking_qr_code_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketbooking",
            name="qr_code_image",
            field=models.ImageField(null=True, upload_to="media/qrcode/"),
        ),
    ]
