# Generated by Django 4.1.2 on 2022-11-26 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_ticketbooking_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program_model',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='program_model',
            name='time_slot',
        ),
    ]
