# Generated by Django 4.1.2 on 2022-11-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0006_remove_program_model_schedule_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketbooking",
            name="qr_image_scanned",
            field=models.BooleanField(default=False),
        ),
    ]
