# Generated by Django 4.1.2 on 2022-11-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0007_ticketbooking_qr_image_scanned"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketbooking",
            name="qr_random_num",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
