# Generated by Django 4.1.2 on 2022-12-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0008_ticketbooking_qr_random_num"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="program_model",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="program_model",
            name="longitude",
        ),
        migrations.AddField(
            model_name="program_model",
            name="map_url",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="ticketbooking",
            name="payment_id",
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
