# Generated by Django 4.1.2 on 2022-12-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0002_committee_members"),
        ("booking", "0009_remove_program_model_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="program_model",
            name="qr_permission",
            field=models.ManyToManyField(null=True, to="register.admin_model"),
        ),
    ]
