# Generated by Django 4.1.2 on 2023-01-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0003_committee_members_username"),
        ("booking", "0010_program_model_qr_permission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program_model",
            name="qr_permission",
            field=models.ManyToManyField(null=True, to="register.committee_members"),
        ),
    ]
