# Generated by Django 4.1.2 on 2023-01-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0012_alter_program_model_qr_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketbooking",
            name="date_booked",
            field=models.DateField(null=True),
        ),
    ]
