# Generated by Django 4.1.2 on 2023-01-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0014_alter_ticketbooking_date_booked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketbooking",
            name="date_booked",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
