# Generated by Django 4.1.2 on 2023-01-25 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0005_admin_model_is_deleted"),
        ("booking", "0015_alter_ticketbooking_date_booked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program_model",
            name="fk_admin_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admin",
                to="register.admin_model",
            ),
        ),
    ]
