# Generated by Django 4.1.2 on 2023-01-25 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_details", "0018_alter_userdetails_user_image"),
        ("booking", "0016_alter_program_model_fk_admin_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketbooking",
            name="fk_user_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user",
                to="user_details.userdetails",
            ),
        ),
    ]
