# Generated by Django 4.1.2 on 2023-03-08 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_details", "0018_alter_userdetails_user_image"),
        ("booking", "0017_alter_ticketbooking_fk_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="program_model",
            name="fk_panchayath",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="panchayath",
                to="user_details.panchayath",
            ),
        ),
        migrations.AddField(
            model_name="program_model",
            name="fk_ward",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ward",
                to="user_details.ward",
            ),
        ),
    ]
