# Generated by Django 4.0.6 on 2022-07-16 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('meeting_link', models.CharField(max_length=255)),
                ('vchr_image', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField(blank=True, null=True)),
                ('date_expired', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=255)),
                ('news_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newstype')),
            ],
        ),
    ]
