# Generated by Django 4.0.6 on 2022-07-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='vchr_image',
        ),
        migrations.AddField(
            model_name='news',
            name='news_image',
            field=models.ImageField(blank=True, max_length=240, null=True, upload_to='news/'),
        ),
    ]
