# Generated by Django 4.0.6 on 2022-07-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_image',
            field=models.ImageField(blank=True, max_length=240, null=True, upload_to='media/news_images/'),
        ),
    ]
