# Generated by Django 4.0.6 on 2022-08-05 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0010_committeetype_committee'),
        ('news', '0005_news_created_by_news_date_modified_news_modified_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='committe_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_details.committeetype'),
        ),
    ]
