# Generated by Django 4.0.6 on 2022-08-06 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0006_news_committe_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingHighligths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('meeting_minutes', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='meeting_link',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='MeetingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/photo/%Y/%m/%d/')),
                ('meeting_highligths', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_photo', to='news.meetinghighligths')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.ImageField(blank=True, null=True, upload_to='media/attendance/%Y/%m/%d/')),
                ('meeting_highligths', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_attendance', to='news.meetinghighligths')),
            ],
        ),
    ]
