# Generated by Django 4.0.6 on 2022-08-27 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0013_remove_userdetails_committee_userdetails_address_and_more'),
        ('news', '0008_meetinghighligths_meeting_attendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='region',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_region', to='user_details.district'),
        ),
    ]
