# Generated by Django 4.1.2 on 2022-12-09 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_details", "0018_alter_userdetails_user_image"),
        ("news", "0011_alter_meetinghighligths_date_added_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="news",
            old_name="region",
            new_name="district_region",
        ),
        migrations.AddField(
            model_name="news",
            name="panchayath_region",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="news_region",
                to="user_details.panchayath",
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="show_all",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="news",
            name="state_region",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="news_region",
                to="user_details.state",
            ),
        ),
    ]
