# Generated by Django 4.1.2 on 2023-01-25 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_details", "0018_alter_userdetails_user_image"),
        ("news", "0012_rename_region_news_district_region_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="district_region",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="news_region",
                to="user_details.district",
            ),
        ),
    ]
