# Generated by Django 4.1.2 on 2023-03-07 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_details", "0018_alter_userdetails_user_image"),
        ("news", "0015_alter_news_committe_type_alter_news_news_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetinghighligths",
            name="committe_type",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user_details.committeetype",
            ),
        ),
        migrations.AddField(
            model_name="meetinghighligths",
            name="district_region",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="meeting_region",
                to="user_details.district",
            ),
        ),
        migrations.AddField(
            model_name="meetinghighligths",
            name="panchayath_region",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="meeting_region",
                to="user_details.panchayath",
            ),
        ),
        migrations.AddField(
            model_name="meetinghighligths",
            name="state_region",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="meeting_region",
                to="user_details.state",
            ),
        ),
        migrations.AddField(
            model_name="meetinghighligths",
            name="ward_region",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="meeting_region",
                to="user_details.ward",
            ),
        ),
    ]
