# Generated by Django 4.1.2 on 2023-03-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0016_meetinghighligths_committe_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetinghighligths",
            name="show_all",
            field=models.BooleanField(default=False),
        ),
    ]
