# Generated by Django 4.1.2 on 2023-03-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0018_meetinghighligths_national_committee"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="national_committee",
            field=models.BooleanField(default=False),
        ),
    ]
