# Generated by Django 4.0.6 on 2022-07-29 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0003_remove_panchayath_block_remove_userdetails_block_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panchayath',
            old_name='District',
            new_name='district',
        ),
    ]
