# Generated by Django 4.0.6 on 2022-08-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0005_alter_userdetails_staff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='designation',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
