# Generated by Django 4.0.6 on 2022-08-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0006_alter_userdetails_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
