# Generated by Django 4.0.6 on 2022-08-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0008_district_created_by_district_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='user_image',
            field=models.ImageField(blank=True, max_length=240, null=True, upload_to='media/user_images/'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='bln_staff',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
