# Generated by Django 4.0.6 on 2022-08-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0010_committeetype_committee'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffrole',
            name='json_sidebar',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
