# Generated by Django 4.0.6 on 2022-08-27 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_details', '0012_userdetails_committee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='committee',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='blood_group',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='committee_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_details.committeetype'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='pin_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='str_panchayath',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='str_ward',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='BloodGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=266)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
