# Generated by Django 4.0.6 on 2022-08-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0013_remove_userdetails_committee_userdetails_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='is_details',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
