# Generated by Django 4.0.6 on 2022-08-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0014_userdetails_is_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='is_details',
            field=models.BooleanField(null=True),
        ),
    ]
