# Generated by Django 4.1.2 on 2022-10-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0017_userdetails_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='user_image',
            field=models.ImageField(blank=True, max_length=240, null=True, upload_to='user_images/'),
        ),
    ]
