# Generated by Django 4.1.2 on 2023-03-08 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_details", "0019_country_state_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="state",
            name="country",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_details.country",
            ),
            preserve_default=False,
        ),
    ]
