# Generated by Django 4.1.2 on 2023-03-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_details", "0020_alter_state_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="code",
            field=models.CharField(default="IN", max_length=255),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(default="India", max_length=255),
        ),
    ]
