# Generated by Django 4.0.6 on 2022-10-27 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_details', '0017_userdetails_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.ImageField(default='default.jpeg', null=True, upload_to='staff/')),
                ('name', models.CharField(max_length=1024)),
                ('phone_number', models.CharField(max_length=12)),
                ('username', models.CharField(max_length=1024, unique=True)),
                ('login_token', models.CharField(default=0, max_length=50)),
                ('created_by', models.PositiveBigIntegerField(null=True)),
                ('updated_by', models.PositiveBigIntegerField(null=True)),
                ('committee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_details.committeetype')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_details.district')),
                ('panchayath', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_details.panchayath')),
                ('staff_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_details.staffrole')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_details.state')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_details.userdetails')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_details.ward')),
            ],
        ),
    ]
