# Generated by Django 4.1.2 on 2022-10-18 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_details', '0016_alter_bloodgroup_date_added_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_image', models.ImageField(upload_to='staff/')),
                ('name', models.CharField(max_length=1024)),
                ('phone_num', models.CharField(max_length=12)),
                ('username', models.CharField(max_length=1024)),
                ('password', models.CharField(max_length=1024)),
                ('confirm_password', models.CharField(max_length=1024)),
                ('committe_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_details.committeetype')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_details.district')),
                ('panchayath', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_details.panchayath')),
                ('staff_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_details.staffrole')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_details.state')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_details.ward')),
            ],
        ),
    ]
