# Generated by Django 4.1.2 on 2022-10-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_model',
            name='login_token',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
