# Generated by Django 4.1.2 on 2023-01-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0002_committee_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="committee_members",
            name="username",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
