# Generated by Django 4.1.2 on 2023-01-12 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_details", "0018_alter_userdetails_user_image"),
        ("register", "0003_committee_members_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="committee_members",
            name="panchayath",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_details.panchayath",
            ),
        ),
        migrations.AlterField(
            model_name="committee_members",
            name="ward",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_details.ward",
            ),
        ),
    ]
