# Generated by Django 4.1.2 on 2022-10-18 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_admin_model_login_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_model',
            name='confirm_password',
        ),
    ]
