# Generated by Django 4.1.2 on 2022-10-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_remove_admin_model_confirm_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_model',
            name='created_by',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='admin_model',
            name='updated_by',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='admin_model',
            name='username',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
