# Generated by Django 4.1.2 on 2023-01-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0004_alter_committee_members_panchayath_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin_model",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
