# Generated by Django 4.1.2 on 2022-10-19 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_admin_model_created_by_admin_model_updated_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_model',
            old_name='staff_image',
            new_name='user_image',
        ),
        migrations.RemoveField(
            model_name='admin_model',
            name='password',
        ),
    ]
