# Generated by Django 4.1.2 on 2022-10-19 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_rename_staff_image_admin_model_user_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_model',
            old_name='committe_type',
            new_name='committee_type',
        ),
        migrations.RenameField(
            model_name='admin_model',
            old_name='phone_num',
            new_name='phone_number',
        ),
    ]
