# Generated by Django 4.1.2 on 2022-10-20 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0017_userdetails_is_admin'),
        ('register', '0007_rename_committe_type_admin_model_committee_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_model',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_details.userdetails'),
        ),
    ]
