# Generated by Django 4.1.2 on 2022-10-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_admin_model_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_model',
            name='user_image',
            field=models.ImageField(null=True, upload_to='staff/'),
        ),
    ]
